Data Import

In [2]:
import pandas as pd
df = pd.read_csv('football.csv')
df_comp = pd.read_csv("competition.csv")

Data Cleaning

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3777 entries, 0 to 3776
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      3777 non-null   int64
 1   date                    3777 non-null   object
 2   home_team               3777 non-null   object
 3   away_team               3777 non-null   object
 4   rank_change_home        3777 non-null   float64
 5   rank_change_away        1735 non-null   float64
 6   home_goals_mean         3777 non-null   float64
 7   home_goals_mean_l5      3777 non-null   float64
 8   home_goals_suf_mean     3753 non-null   float64
 9   home_goals_suf_mean_l5  3777 non-null   float64
 10  home_rank_mean          3777 non-null   float64
 11  home_rank_mean_l5       3777 non-null   float64
 12  home_points_mean        3763 non-null   float64
 13  home_points_mean_l5     3777 non-null   float64
 14  away_goals_mean         3777 non-null   float64
 15  away_goals_mean_l5      3777 non-null   float64
 16  away_goals_suf_mean     3760 non-null   float64
 17  away_goals_suf_mean_l5  3777 non-null   float64
 18  away_rank_mean          3777 non-null   float64
 19  away_rank_mean_l5       3777 non-null   float64
 20  away_points_mean        3777 non-null   float64
 21  away_points_mean_l5     3777 non-null   float64
 22  target                  3777 non-null   int64
 23  match_type              3777 non-null   object
dtypes: float64(18), int64(2), object(4)
memory usage: 708.3+ KB

In [4]:
df

,id,date,home_team,away_team,rank_change_home,rank_change_away,home_goals_mean,home_goals_mean_l5,home_goals_suf_mean,home_goals_suf_mean_l5,...,away_goals_mean,away_goals_mean_l5,away_goals_suf_mean,away_goals_suf_mean_l5,away_rank_mean,away_rank_mean_l5,away_points_mean,away_points_mean_l5,target,match_type
0,2221,2021-09-09,Brazil,Peru,-1.0,-5.0,2.028571,0.8,0.371429,0.4,...,1.027778,1.4,1.583333,1.6,24.388889,21.2,8.16,31.28,0,Friendly
1,507,2019-05-29,Comoros,Mauritius,5.0,NaN,1.166667,1.2,1.666667,1.8,...,1.200000,1.2,1.200000,1.2,159.800000,159.8,-6.00,-6.00,0,Friendly
2,1545,2020-11-18,Serbia,Russia,-1.0,NaN,1.608696,1.2,1.347826,1.2,...,2.136364,0.8,1.045455,1.2,65.681818,62.0,70.00,-5.00,0,Friendly
3,2067,2021-09-01,Senegal,Togo,-1.0,NaN,1.482759,1.4,0.620690,0.8,...,0.857143,0.8,1.214286,1.2,104.500000,82.0,-31.86,-22.86,0,Friendly
4,4448,2024-03-22,Peru,Nicaragua,-2.0,NaN,0.968750,0.2,1.265625,1.6,...,1.600000,3.0,1.244444,0.2,132.200000,169.4,-21.30,23.59,0,Competition
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,2020,2021-07-12,Jamaica,Suriname,0.0,NaN,2.000000,1.0,1.090909,2.0,...,3.181818,3.4,NaN,1.0,154.636364,153.6,53.43,37.43,0,Friendly
3773,696,2019-06-28,Colombia,Chile,1.0,NaN,1.909091,2.0,0.545455,0.0,...,1.545455,1.8,1.272727,0.8,39.090909,44.2,-9.00,-4.00,1,Friendly
3774,2325,2021-10-11,Mozambique,Cameroon,3.0,4.0,1.000000,0.6,1.153846,1.6,...,1.086957,1.2,0.478261,0.2,88.260870,86.2,-11.54,-22.54,1,Friendly
3775,3301,2022-11-19,Colombia,Paraguay,0.0,NaN,1.319149,2.4,0.872340,0.6,...,0.909091,0.8,1.272727,0.6,34.886364,31.2,-28.23,5.47,0,Competition
3776,3117,2022-09-22,Australia,New Zealand,0.0,NaN,1.862069,0.8,0.586207,1.0,...,1.750000,1.2,0.833333,0.4,104.833333,85.8,49.07,44.41,0,Competition

Drop Unnecessary Columns

In [5]:

df = df.drop(columns=['date','id','home_team','away_team','match_type','rank_change_away'])

Impute Missing Values

In [6]:
df.isna().sum()

rank_change_home           0
home_goals_mean            0
home_goals_mean_l5         0
home_goals_suf_mean       24
home_goals_suf_mean_l5     0
home_rank_mean             0
home_rank_mean_l5          0
home_points_mean          14
home_points_mean_l5        0
away_goals_mean            0
away_goals_mean_l5         0
away_goals_suf_mean       17
away_goals_suf_mean_l5     0
away_rank_mean             0
away_rank_mean_l5          0
away_points_mean           0
away_points_mean_l5        0
target                     0
dtype: int64

In [7]:
df['home_goals_suf_mean'] = df['home_goals_suf_mean'].fillna(df['home_goals_suf_mean'].median())
df['home_points_mean'] = df['home_points_mean'].fillna(df['home_points_mean'].median())
df['away_goals_suf_mean'] = df['away_goals_suf_mean'].fillna(df['away_goals_suf_mean'].median())

In [8]:
df

,rank_change_home,home_goals_mean,home_goals_mean_l5,home_goals_suf_mean,home_goals_suf_mean_l5,home_rank_mean,home_rank_mean_l5,home_points_mean,home_points_mean_l5,away_goals_mean,away_goals_mean_l5,away_goals_suf_mean,away_goals_suf_mean_l5,away_rank_mean,away_rank_mean_l5,away_points_mean,away_points_mean_l5,target
0,-1.0,2.028571,0.8,0.371429,0.4,33.057143,25.4,140.67,55.02,1.027778,1.4,1.583333,1.6,24.388889,21.2,8.16,31.28,0
1,5.0,1.166667,1.2,1.666667,1.8,76.833333,82.8,19.00,11.00,1.200000,1.2,1.200000,1.2,159.800000,159.8,-6.00,-6.00,0
2,-1.0,1.608696,1.2,1.347826,1.2,54.130435,44.0,30.00,3.00,2.136364,0.8,1.045455,1.2,65.681818,62.0,70.00,-5.00,0
3,-1.0,1.482759,1.4,0.620690,0.8,97.551724,113.6,44.45,0.00,0.857143,0.8,1.214286,1.2,104.500000,82.0,-31.86,-22.86,0
4,-2.0,0.968750,0.2,1.265625,1.6,31.531250,34.8,-2.43,-28.63,1.600000,3.0,1.244444,0.2,132.200000,169.4,-21.30,23.59,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3772,0.0,2.000000,1.0,1.090909,2.0,103.909091,71.0,32.65,-8.35,3.181818,3.4,1.181818,1.0,154.636364,153.6,53.43,37.43,0
3773,1.0,1.909091,2.0,0.545455,0.0,33.000000,39.4,17.00,7.00,1.545455,1.8,1.272727,0.8,39.090909,44.2,-9.00,-4.00,1
3774,3.0,1.000000,0.6,1.153846,1.6,113.538462,103.2,-17.41,-2.96,1.086957,1.2,0.478261,0.2,88.260870,86.2,-11.54,-22.54,1
3775,0.0,1.319149,2.4,0.872340,0.6,31.957447,62.6,41.07,18.18,0.909091,0.8,1.272727,0.6,34.886364,31.2,-28.23,5.47,0
3776,0.0,1.862069,0.8,0.586207,1.0,87.000000,51.4,31.29,-24.57,1.750000,1.2,0.833333,0.4,104.833333,85.8,49.07,44.41,0

Split Data

In [9]:
from sklearn.model_selection import train_test_split
x=df.drop(columns=['target'])
y=df['target']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=1)

Scale Data for Fair Comparison

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

Train Ridge & Lasso Models

In [11]:
from sklearn.linear_model import Ridge, Lasso

ridge = Ridge(alpha=0.1)
lasso = Lasso(alpha=0.1, max_iter=1000)

ridge.fit(x_train, y_train)
lasso.fit(x_train, y_train)

Lasso(alpha=0.1)

Compare Ridge vs Lasso Performance

In [12]:
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score
y_pred_ridge = ridge.predict(x_test)
y_pred_lasso = lasso.predict(x_test)

y_pred_ridge_bin = (y_pred_ridge > 0.5).astype(int)
y_pred_lasso_bin = (y_pred_lasso > 0.5).astype(int)


rmse_ridge = np.sqrt(mean_squared_error(y_test, y_pred_ridge_bin))
r2_ridge = r2_score(y_test, y_pred_ridge_bin)
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso_bin))
r2_lasso = r2_score(y_test, y_pred_lasso_bin)

print("RIDGE: RMSE =", round(rmse_ridge, 3), "R² =", round(r2_ridge, 3))
print("LASSO: RMSE =", round(rmse_lasso, 3), "R² =", round(r2_lasso, 3))
print("Ridge Accuracy TEST:", (y_pred_ridge_bin == y_test).mean())
print("LASSO Accuracy TEST:", (y_pred_lasso_bin == y_test).mean())

RIDGE: RMSE = 0.554 R² = -0.229
LASSO: RMSE = 0.693 R² = -0.923
Ridge Accuracy TEST: 0.6931216931216931
LASSO Accuracy TEST: 0.5198412698412699

Data Cleaning Competition

In [13]:
df_comp

,id,date,home_team,away_team,rank_change_home,rank_change_away,home_goals_mean,home_goals_mean_l5,home_goals_suf_mean,home_goals_suf_mean_l5,...,home_points_mean_l5,away_goals_mean,away_goals_mean_l5,away_goals_suf_mean,away_goals_suf_mean_l5,away_rank_mean,away_rank_mean_l5,away_points_mean,away_points_mean_l5,match_type
0,3233,2022-09-27,Norway,Serbia,0.0,0.0,1.761905,1.400000,0.880952,1.000000,...,25.07,1.800000,2.200000,1.111111,1.0,54.533333,42.0,90.53,2.00,Friendly
1,2432,2021-11-13,Malawi,Cameroon,5.0,-4.0,0.709677,0.600000,1.096774,1.400000,...,-8.89,1.083333,1.400000,0.458333,0.2,89.416667,82.8,-11.54,-0.41,Friendly
2,245,2018-11-18,San Marino,Belarus,5.0,-2.0,0.000000,0.000000,2.800000,2.800000,...,-14.00,1.600000,1.600000,0.000000,0.0,143.400000,143.4,1.00,1.00,Friendly
3,465,2019-03-24,El Salvador,Jamaica,3.0,0.0,1.500000,1.400000,1.333333,1.400000,...,-5.00,2.600000,2.600000,1.200000,1.2,148.600000,148.6,1.00,1.00,Friendly
4,2419,2021-11-12,Austria,Israel,3.0,0.0,1.421053,1.200000,1.052632,1.400000,...,-30.30,1.806452,2.600000,1.612903,2.2,60.870968,74.6,54.33,22.11,Friendly
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
940,3007,2022-06-11,Uzbekistan,Maldives,-2.0,-1.0,1.575758,2.000000,1.090909,1.200000,...,4.28,1.000000,1.400000,1.826087,1.8,146.739130,177.4,-22.50,-5.42,Friendly
941,108,2018-10-14,Poland,Italy,0.0,-1.0,1.333333,1.333333,1.666667,1.666667,...,-1.00,0.666667,0.666667,1.000000,1.0,18.000000,18.0,-6.00,-6.00,Friendly
942,4398,2024-03-21,Israel,Iceland,0.0,2.0,1.711538,1.000000,1.615385,0.800000,...,12.53,1.144928,1.800000,1.623188,1.2,64.898551,87.8,-132.61,-13.54,Friendly
943,3399,2022-12-23,Oman,Syria,0.0,0.0,1.188679,0.600000,0.886792,0.600000,...,-3.87,1.081633,0.200000,1.387755,1.4,89.204082,69.4,-72.08,-9.11,Competition
944,1168,2019-11-18,Liechtenstein,Bosnia and Herzegovina,-1.0,2.0,0.600000,0.400000,2.666667,3.000000,...,11.00,1.466667,2.400000,1.266667,2.0,52.066667,81.8,-17.00,-18.00,Friendly

In [14]:
df_comp = df_comp.drop(columns=['date','home_team','away_team','match_type','rank_change_away'])

In [15]:
x_comp = df_comp.drop(columns=['id'])
x_comp_scaled = scaler.transform(x_comp)

y_comp_pred_ridge = ridge.predict(x_comp_scaled)
y_comp_pred_lasso = lasso.predict(x_comp_scaled)

y_comp_pred_ridge_bin = (y_comp_pred_ridge > 0.5).astype(int)

y_comp_pred_lasso_bin = (y_comp_pred_lasso > 0.5).astype(int)

Generate Kaggle Submission

In [16]:
Linearsoum = pd.DataFrame({'id': df_comp['id'], 'target': y_comp_pred_lasso_bin})
Linearsoum.to_csv('submission_lasso.csv', index=False)

Improve Ridge Model Performance

In [17]:
top10 = pd.DataFrame({
    'Colonne': df.columns[1:], 
    'Coef': ridge.coef_
}).sort_values('Coef', key=abs, ascending=False).head(10)

print(top10['Colonne'].tolist())

['away_rank_mean_l5', 'home_rank_mean_l5', 'away_goals_suf_mean_l5', 'home_goals_mean_l5', 'home_goals_suf_mean_l5', 'away_goals_mean_l5', 'home_rank_mean', 'home_points_mean_l5', 'away_points_mean_l5', 'away_rank_mean']

In [18]:
from sklearn.metrics import accuracy_score
# 1️⃣ Sélectionne TES 10 colonnes
top10_cols = ['away_rank_mean_l5', 'home_rank_mean_l5', 'away_goals_suf_mean_l5', 
              'home_goals_mean_l5', 'home_goals_suf_mean_l5', 'away_goals_mean_l5', 
              'home_rank_mean', 'home_points_mean_l5', 'away_points_mean_l5', 'away_rank_mean']

x_top10 = df[top10_cols]

# 2️⃣ Split
x_train_top10, x_test_top10, y_train, y_test = train_test_split(x_top10, y, test_size=0.2)

x_train_top10, x_test_top10, y_train, y_test = train_test_split(x_top10, y, test_size=0.2)

scaler_top10 = StandardScaler()
x_train_top10_scaled = scaler_top10.fit_transform(x_train_top10)
x_test_top10_scaled = scaler_top10.transform(x_test_top10)

# Ridge TOP 10
ridge_top10 = Ridge(alpha=0.001,random_state=1)
ridge_top10.fit(x_train_top10_scaled, y_train)

# TEST
y_pred_top10 = ridge_top10.predict(x_test_top10_scaled)
print("Accuracy TOP 10:", accuracy_score(y_test, (y_pred_top10 > 0.5).astype(int)))

Accuracy TOP 10: 0.705026455026455

In [19]:
x_comp_top10 = df_comp[top10_cols]

x_comp_top10_scaled = scaler_top10.transform(x_comp_top10)

y_comp_pred_ridge_top10 = ridge_top10.predict(x_comp_top10_scaled)
y_comp_pred_ridge_top10_bin = (y_comp_pred_ridge_top10 > 0.5).astype(int)

In [20]:
Linearsoum = pd.DataFrame({'id': df_comp['id'], 'target': y_comp_pred_ridge_top10_bin})
Linearsoum.to_csv('submission_ridge2.csv', index=False)